### PR TITLE
Add a hook to get longitude and latitude

### PR DESCRIPTION
**Pull request by fernandoamz**
### Implements
Add a new hook to get the geolocalisation from the browser, the hook will get the permissions and it will return the values.

### CODE REVIEW

**Comment by sairaj2119** [comment]
Yea assign me I fill send a PR

**Comment by aromalanil** [comment]
@fernandoamz Please add the description, parameters and return value as per [JSdoc](https://jsdoc.app/) guidelines.

**Comment by fernandoamz** [comment]
@aromalanil, I send the correction

**Comment by aromalanil** [comment]
@fernandoamz Check out other suggestions also and remove the space between comment and the function.

**Comment by aromalanil** [comment]
@fernandoamz I hope you can see the changes I have requested. If you can't I will mention it here.

- An array is not needed for single return value so you can use
 ```js
return latLong
```

- Use meaning full variable name, I would suggest using `geoLocation` instead of `latLong`.

- A more elegent way to define object would be
```js
let userPosition = {
      latitude = position.coords.latitude; 
      longitude = position.coords.longitude;
};       
```
- The boolean `geolocation` passed to the function is unnecessary.

**Comment by fernandoamz** [comment]
Oh, nice suggestions! I will fix it. thanks so much

**Comment by aromalanil** [comment]
@fernandoamz I didn't notice this but did you really intend to use word Geo Localisation. The apt word would be Geo Location

**Comment by fernandoamz** [comment]
Hey!, @aromalanil, I followed up all your suggestions. Let me know if I need to do some other changes!.

**Comment by aromalanil** [comment]
LGTM 👍🏻

**Comment by aromalanil** [comment]
@all-contributors please add @fernandoamz for code and doc

**Review by aromalanil — COMMENTED** [review]
Changes made. approved for merging

**Pull request merged**
